metadata:
  labels:
    environment: dev

openmrs:
  enabled: true
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: true
crater:
  enabled: true
reports:
  enabled: true
  config:
    OPENMRS_HOST: "bahmni-openmrs"
  image:
    repository: bahmniindiadistro
    name: reports
    tag: 1.0.0-1
hiu:
  enabled: true
hiu-db:
  enabled: true
hiu-ui:
  enabled: true
hip:
  enabled: true
otp-service:
  enabled: true
abdm-db:
  enabled: true
rabbit-mq:
  enabled: true

rabbitmq:
  auth:
    erlangCookie: bahmni
