global:
  TZ: "UTC"

metadata:
  labels:
    environment: local
  ingress:
    PROXY_BODY_SIZE: '7m'
    ABDM_PROXY_BODY_SIZE: '30m'
ingress:
  host: bahmni.k8s

openmrs:
  enabled: true
  secrets:
    OMRS_DB_USERNAME: openmrs-user
    OMRS_DB_PASSWORD: password
    OMRS_DB_HOSTNAME: openmrsdb
  config:
    OMRS_DB_NAME: openmrs
    DEBUG: true
    OMRS_CREATE_TABLES: true
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: true
crater:
  enabled: true
  config:
    APP_URL: http://payments-bahmni.k8s
    DB_DATABASE: crater
    DB_HOST: openmrsdb
    DB_PORT: 3306
    SANCTUM_STATEFUL_DOMAINS: payments-bahmni.k8s
    SESSION_DOMAIN: payments-bahmni.k8s
    AUTO_INSTALL: 'true'
    ADMIN_NAME: Super Man
    COMPANY_NAME: Bahmni
    COMPANY_SLUG: bahmni
    COUNTRY_ID: 101
  secrets:
    DB_USERNAME: 'crater-user'
    DB_PASSWORD: 'password'
    ADMIN_EMAIL: 'superman@bahmni.org'
    ADMIN_PASSWORD: 'Crater123'
reports:
  enabled: true
  config:
    OPENMRS_HOST: 'openmrs'
    OPENMRS_DB_NAME: openmrs
    REPORTS_DB_NAME: reports
  secrets:
    OPENMRS_DB_HOST: openmrsdb
    OPENMRS_DB_USERNAME: openmrs-user
    OPENMRS_DB_PASSWORD: password
    REPORTS_DB_SERVER: openmrsdb
    REPORTS_DB_USERNAME: reports-user
    REPORTS_DB_PASSWORD: password
patient-documents:
  enabled: true
  config:
    OPENMRS_HOST: 'openmrs'

appointments:
  enabled: true

crater-atomfeed:
  enabled: true

implementer-interface:
  enabled: true

bahmni-metabase:
  enabled: true
  config:
    MB_DB_TYPE: postgres
    MB_DB_DBNAME: 'metabase'
    MB_DB_PORT:  5432
    OPENMRS_DB_NAME: 'openmrs'
    MART_DB_NAME: martdb
  secrets:
    MB_ADMIN_EMAIL: 'admin@mybahmni.org'
    MB_ADMIN_FIRST_NAME: 'Admin'
    MB_ADMIN_PASSWORD: 'Admin@123'
    MB_DB_USER: 'metabase-user'
    MB_DB_PASS: 'password'
    MB_DB_HOST: 'bahmni-local-postgresql'
    OPENMRS_DB_HOST: 'openmrsdb'
    OPENMRS_DB_USERNAME: 'openmrs-user'
    OPENMRS_DB_PASSWORD: 'password'
    MART_DB_HOST: 'bahmni-local-postgresql'
    MART_DB_USERNAME: 'bahmni-mart'
    MART_DB_PASSWORD: 'password'

postgresql:
  enabled: false

bahmni-mart:
  enabled: false
  config:
    MART_DB_NAME: martdb
    OPENMRS_DB_NAME: openmrs
  secrets:
    MART_DB_HOST: "bahmni-local-postgresql"
    MART_DB_USERNAME: "bahmni-mart"
    MART_DB_PASSWORD: "password"
    OPENMRS_DB_HOST: "openmrsdb"
    OPENMRS_DB_USERNAME: "openmrs-user"
    OPENMRS_DB_PASSWORD: "password"
