apiVersion: v2
name: bahmni-india-distro
description: Helm Umbrella chart for Bahmni India Distribution
type: application
version: 1.0.0

dependencies:
  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: bahmni-openmrs
    version: ~1.0.0-0
    condition: openmrs.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: bahmni-web
    version: ~1.0.0-0
    condition: bahmni-web.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: bahmni-lab
    version: ~1.0.0-0
    condition: bahmni-lab.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: crater
    version: ~1.0.0-0
    condition: crater.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: reports
    version: ~1.0.0-0
    condition: reports.enabled
