apiVersion: v2
name: bahmni
description: Helm Umbrella chart for Bahmni
type: application
version: 1.0.0

dependencies:
  - repository: https://bahmni.github.io/helm-charts
    name: openmrs
    version: ~1.0.0-0
    condition: openmrs.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: bahmni-web
    version: ~1.0.0-0
    condition: bahmni-web.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: bahmni-lab
    version: ~1.0.0-0
    condition: bahmni-lab.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: crater
    version: ~1.0.0-0
    condition: crater.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: reports
    version: ~1.0.0-0
    condition: reports.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: patient-documents
    version: ~1.0.0-0
    condition: patient-documents.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: crater-atomfeed
    version: ~1.0.0-0
    condition: crater-atomfeed.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: appointments
    version: ~1.0.0-0
    condition: appointments.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: implementer-interface
    version: ~1.0.0-0
    condition: implementer-interface.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: clinic-config
    version: ~1.0.0-0

  - repository: https://bahmni.github.io/helm-charts
    name: bahmni-metabase
    version: ~1.0.0-0
    condition: bahmni-metabase.enabled
    
  - repository: https://charts.bitnami.com/bitnami
    name: postgresql
    version: 12.1.2
    condition: postgresql.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: bahmni-mart
    version: ~1.0.0-0
    condition: bahmni-mart.enabled
