apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: {{ .Values.DB_HOST | b64enc | quote }}
  DB_ROOT_USERNAME: {{ .Values.DB_ROOT_USERNAME | b64enc | quote }}
  DB_ROOT_PASSWORD: {{ .Values.DB_ROOT_PASSWORD | b64enc | quote }}
  OPENMRS_DB_NAME: {{ printf "%s_%s" "openmrs" .Values.environment | b64enc | quote }}
  OPENMRS_DB_USERNAME: {{ .Values.OPENMRS_DB_USERNAME | b64enc | quote }}
  OPENMRS_DB_PASSWORD: {{ .Values.OPENMRS_DB_PASSWORD | b64enc | quote }}
  REPORTS_DB_NAME: {{ printf "%s_%s" "bahmni_reports" .Values.environment | b64enc | quote }}
  REPORTS_DB_USERNAME: {{ .Values.REPORTS_DB_USERNAME | b64enc | quote }}
  REPORTS_DB_PASSWORD: {{ .Values.REPORTS_DB_PASSWORD | b64enc | quote }}
  CRATER_DB_NAME: {{ printf "%s_%s" "crater" .Values.environment | b64enc | quote }}
  CRATER_DB_USERNAME: {{ .Values.CRATER_DB_USERNAME | b64enc | quote }}
  CRATER_DB_PASSWORD: {{ .Values.CRATER_DB_PASSWORD | b64enc | quote }}