apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  # name: bahmni-aws-ingress-class
  name: bahmni-nginx-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true'
spec:
  # controller: ingress.k8s.aws/alb
  controller: k8s.io/ingress-nginx
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bahmni-ingress
  labels:
    environment: {{ .Values.metadata.labels.environment }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if index .Values "bahmni-web" "enabled" }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bahmni-web
                port:
                  number: 8091
          {{- end }}

          {{- if index .Values "bahmni-lab" "enabled" }}
          - path: /lab
            pathType: Prefix
            backend:
              service:
                name: bahmni-lab
                port:
                  number: 8090
          {{- end }}

          {{- if .Values.reports.enabled }}
          - path: /bahmnireports
            pathType: Prefix
            backend:
              service:
                name: reports
                port:
                  number: 8051
          {{- end }}

          {{- if .Values.hiu.enabled }}
          - path: /hiu-api
            pathType: Prefix
            backend:
              service:
                name: hiu
                port:
                  number: 9053
          {{- end }}

          {{- if index .Values "hiu-ui" "enabled" }}
          - path: /hiuser
            pathType: Prefix
            backend:
              service:
                name: hiu-ui
                port:
                  number: 5000
          {{- end }}

          {{- if .Values.hip.enabled }}
          - path: /hip
            pathType: Prefix
            backend:
              service:
                name: hip
                port:
                  number: 8000
          {{- end }}

          {{- if index .Values "otp-service" "enabled" }}
          - path: /otp-service
            pathType: Prefix
            backend:
              service:
                name: otp-service
                port:
                  number: 8092
          {{- end }}

    - host: payments-{{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.crater.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crater-nginx
                port:
                  number: 80
          {{- end }}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openmrs-ingress
  labels:
    environment: {{ .Values.metadata.labels.environment }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Set-Cookie "reporting_session=$cookie_JSESSIONID;Domain=$http_host;Path=/;Max-Age=86400";
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.openmrs.enabled }}
          - path: /openmrs
            pathType: Prefix
            backend:
              service:
                name: bahmni-openmrs
                port:
                  number: 8080
          {{- end }}
