name: Deploy to dev environment


on:
  push:
    branches: 
      - BAH-1809
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: bahmni-cluster-dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Helm Dependency Update
        run: helm dependency update
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ${{ secrets.BAHMNI_AWS_REGION }}
          role-to-assume: ${{ secrets.BAHMNI_INFRA_ADMIN_ROLE }}
          role-duration-seconds: 900 # 15 mins
          role-session-name: BahmniInfraAdminSession
      - name: Authorise Kubectl with EKS
        run: aws eks update-kubeconfig --name $CLUSTER_NAME
      - name: Install Nginx Ingress
        run: |
          wget https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
          sed  -i.bak "s/XXX.XXX.XXX\/XX/10.0.0.0\/16/" deploy.yaml
          sed  -i.bak "s/arn:aws:acm:us-west-2:XXXXXXXX:certificate\/XXXXXX-XXXXXXX-XXXXXXX-XXXXXXXX/${{ secrets.MYBAHMNI_CERT_ARN }}/" deploy.yaml
          kubectl apply -f deploy.yaml
      - name: Upsert Route53 A record with INGRESS_DNS
        run: |
          INGRESS_DNS=$(kubectl -n ingress-nginx  get svc ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
          jq --arg ingress_dns "$INGRESS_DNS" '.Changes[].ResourceRecordSet.AliasTarget.DNSName = $ingress_dns' aws/route53/lite.mybahmni.in.json > recordset
          aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.HOSTED_ZONE_ID }} --change-batch file://recordset
      - name: Get and store ssm secrets
        run: |
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/rds/mysql/host" --query "Parameter.Value" --output text)">RDS_HOST
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/rds/mysql/username" --query "Parameter.Value" --output text)">RDS_USERNAME
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/rds/mysql/password" --query "Parameter.Value" --output text)">RDS_PASSWORD
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/openmrs/DB_USERNAME" --query "Parameter.Value" --output text)"> OPENMRS_DB_USERNAME
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/openmrs/DB_PASSWORD" --query "Parameter.Value" --output text)">  OPENMRS_DB_PASSWORD
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/reports/DB_USERNAME" --query "Parameter.Value" --output text)"> REPORTS_DB_USERNAME
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/reports/DB_PASSWORD" --query "Parameter.Value" --output text)">REPORTS_DB_PASSWORD
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/crater/DB_USERNAME" --query "Parameter.Value" --output text)">CRATER_DB_USERNAME
          echo "$(aws ssm get-parameter --with-decryption --name "/dev/crater/DB_PASSWORD" --query "Parameter.Value" --output text)"> CRATER_DB_PASSWORD    
      - name: Setup databases
        run: |
          helm install db-setup db-setup --repo https://bahmni.github.io/helm-charts --devel --wait --wait-for-jobs --atomic --timeout 1m \
          --set DB_HOST=$(cat RDS_HOST) \
          --set DB_ROOT_USERNAME=$(cat RDS_USERNAME) \
          --set DB_ROOT_PASSWORD=$(cat RDS_PASSWORD) \
          --set databases.openmrs.DB_NAME=openmrs_test \
          --set databases.openmrs.USERNAME=$(cat OPENMRS_DB_USERNAME) \
          --set databases.openmrs.PASSWORD=$(cat OPENMRS_DB_PASSWORD) \
          --set databases.crater.DB_NAME=crater_test \
          --set databases.crater.USERNAME=$(cat CRATER_DB_USERNAM) \
          --set databases.crater.PASSWORD=$(cat CRATER_DB_PASSWORD) \
          --set databases.reports.DB_NAME=bahmni_reports_test \
          --set databases.reports.USERNAME=$(cat REPORTS_DB_USERNAME) \
          --set databases.reports.PASSWORD=$(cat REPORTS_DB_PASSWORD)

      - name: Deleting db-setup helm release
        run: helm uninstall db-setup

      - name: Helm Upgrade
        run: |
          MQ_USERNAME=$(aws ssm get-parameter --with-decryption --name "/nonprod/rabbitmq/USERNAME" --query "Parameter.Value" --output text)
          MQ_PASSWORD=$(aws ssm get-parameter --with-decryption --name "/nonprod/rabbitmq/PASSWORD" --query "Parameter.Value" --output text)
          PSQL_PASSWORD=$(aws ssm get-parameter --with-decryption --name "/nonprod/psql/DB_PASSWORD" --query "Parameter.Value" --output text)
          GATEWAY_CLIENT_ID=$(aws ssm get-parameter --with-decryption --name "/nonprod/abdm/GATEWAY_CLIENT_ID" --query "Parameter.Value" --output text)
          GATEWAY_CLIENT_SECRET=$(aws ssm get-parameter --with-decryption --name "/nonprod/abdm/GATEWAY_CLIENT_SECRET" --query "Parameter.Value" --output text)
          helm upgrade bahmni-dev . \
          --set bahmni-openmrs.secrets.DB_ROOT_USERNAME=$(cat RDS_USERNAME) \
          --set bahmni-openmrs.secrets.DB_ROOT_PASSWORD=$(cat RDS_PASSWORD) \
          --set bahmni-openmrs.secrets.DB_USERNAME=$(cat RDS_USERNAME) \
          --set bahmni-openmrs.secrets.DB_PASSWORD=$(cat RDS_PASSWORD) \
          --set bahmni-openmrs.secrets.DB_HOST=$(cat RDS_HOST) \
          --set reports.secrets.OPENMRS_DB_HOST=$(cat RDS_HOST) \
          --set reports.secrets.OPENMRS_DB_USERNAME=$(cat RDS_USERNAME) \
          --set reports.secrets.OPENMRS_DB_PASSWORD=$(cat RDS_PASSWORD) \
          --set reports.secrets.REPORTS_DB_SERVER=$(cat RDS_HOST) \
          --set reports.secrets.REPORTS_DB_USERNAME=$(cat RDS_USERNAME) \
          --set reports.secrets.REPORTS_DB_PASSWORD=$(cat RDS_PASSWORD) \
          --set hip.secrets.GATEWAY_CLIENT_ID=$GATEWAY_CLIENT_ID \
          --set hip.secrets.GATEWAY_CLIENT_SECRET=$GATEWAY_CLIENT_SECRET \
          --set hip.secrets.OPENMRS_PASSWORD=Admin123 \
          --set hip.config.BAHMNI_URL=https://lite.mybahmni.in/openmrs \
          --set hiu.secrets.HIU_CLIENT_ID=$GATEWAY_CLIENT_ID \
          --set hiu.secrets.HIU_CLIENT_SECRET=$GATEWAY_CLIENT_SECRET \
          --set hiu.config.DATA_PUSH_URL=https://lite.mybahmni.in/hiu-api/data/notification \
          --set hiu-ui.config.BACKEND_BASE_URL=https://lite.mybahmni.in \
          --set global.postgresql.auth.postgresPassword=$PSQL_PASSWORD \
          --set rabbitmq.auth.username=$MQ_USERNAME \
          --set rabbitmq.auth.password=$MQ_PASSWORD \
          --set ingress.host=lite.mybahmni.in \
          --values=values/dev.yaml \
          --install
  notification:
    name: Slack notification
    needs:
      - deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Success
        if: ${{ needs.deploy.result == 'success' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":">🟢 Bahmni India Distro deployed. \n>*Bahmni* https://lite.mybahmni.in \n>*Payments* https://payments-lite.mybahmni.in \n> <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|Umbrella Chart Job #${{github.run_id}}>"}' ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Failure
        if: ${{ needs.deploy.result == 'failure' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"🔴 Bahmni India Distro deployment failed!!! This is where you go look what happened → <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|Umbrella Chart Job #${{github.run_id}}>"}' ${{ secrets.SLACK_WEBHOOK_URL }}
