name: Trivy Security Scan

on:
  push:
    branches:
      - BAH-2136
    paths:
      - .github/workflows/trivy-scan.yaml

  workflow_dispatch:

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: bahmni-cluster-nonprod
    steps:
      - name: Setup Trivy
        run: brew install aquasecurity/trivy/trivy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ${{ secrets.BAHMNI_AWS_REGION }}
          role-to-assume: ${{ secrets.BAHMNI_INFRA_ADMIN_ROLE }}
          role-duration-seconds: 900 # 15 mins
          role-session-name: BahmniInfraAdminSession
      - name: Authorise Kubectl with EKS
        run: aws eks update-kubeconfig --name $CLUSTER_NAME

      - name: Run Trivy Scan
        run: trivy k8s --report=summary --timeout=1h cluster

