name: Trivy Security Scan

on:
  push:
    branches:
      - BAH-2136
    paths:
      - .github/workflows/trivy-scan.yaml

  workflow_dispatch:

env:
  CLUSTER_NAME: bahmni-cluster-nonprod

jobs:
  get-namespaces:
    name: Get Namespaces
    runs-on: ubuntu-latest
    outputs:
      namespaces: ${{ steps.get-namespaces.outputs.namespaces }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ${{ secrets.BAHMNI_AWS_REGION }}
          role-to-assume: ${{ secrets.BAHMNI_INFRA_ADMIN_ROLE }}
          role-duration-seconds: 900 # 15 mins
          role-session-name: BahmniInfraAdminSession
      - name: Authorise Kubectl with EKS
        run: aws eks update-kubeconfig --name $CLUSTER_NAME
      - name: Get namespaces list
        id: get-namespaces
        run: |
          NAMESPACES=$(kubectl get ns -o json | jq -c ".items[] | .metadata.name" | jq -s .)
          echo $NAMESPACES
          echo ::set-output name=namespaces::${NAMESPACES}

  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: [get-namespaces]
    strategy:
      matrix:
        namespaces: ${{ fromJson(needs.get-namespaces.outputs.namespaces) }}
    steps:
      - name: Setup Trivy
        run: brew install aquasecurity/trivy/trivy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ${{ secrets.BAHMNI_AWS_REGION }}
          role-to-assume: ${{ secrets.BAHMNI_INFRA_ADMIN_ROLE }}
          role-duration-seconds: 900 # 15 mins
          role-session-name: BahmniInfraAdminSession
      - name: Authorise Kubectl with EKS
        run: aws eks update-kubeconfig --name $CLUSTER_NAME

      - name: Create reports directory
        run: mkdir reports

      - name: Run Trivy Detailed Scan for Critical Vulnerabilities
        run: trivy k8s --no-progress --severity CRITICAL --report=all --namespace ${{ matrix.namespaces }} --timeout=1h all -o reports/critical-vulnerabilities.txt
      - name: Run Trivy Detailed Scan for High Vulnerabilities
        run: trivy k8s --no-progress --severity HIGH --report=all --namespace ${{ matrix.namespaces }} --timeout=1h all -o reports/high-vulnerabilities.txt
      - name: Run Trivy Detailed Scan for Medium Vulnerabilities
        run: trivy k8s --no-progress --severity MEDIUM --report=all --namespace ${{ matrix.namespaces }} --timeout=1h all -o reports/medium-vulnerabilities.txt
      - name: Run Trivy Detailed Scan for Low Vulnerabilities
        run: trivy k8s --no-progress --severity LOW --report=all --namespace ${{ matrix.namespaces }} --timeout=1h all -o reports/low-vulnerabilities.txt
      - name: Run Trivy Detailed Scan for Unknown Vulnerabilities
        run: trivy k8s --no-progress --severity UNKNOWN --report=all --namespace ${{ matrix.namespaces }} --timeout=1h all -o reports/unknown-vulnerabilities.txt

      - name: Run Trivy Summary Scan
        run: trivy k8s --no-progress --report=summary --namespace ${{ matrix.namespaces }} --timeout=1h all -o reports/trivy-summary.txt

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.namespaces }}
          path: reports/

  upload-report:
    runs-on: ubuntu-latest
    needs: [trivy-scan]
    steps:
      - id: getEpoch
        name: Run Epoch
        run: |
          export EPOCH=$(date +%s)
          echo "::set-output name=epoch::${EPOCH}"
      - name: Checkout reports branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download Reports
        uses: actions/download-artifact@v3
        with:
          path: trivy-reports/${{ steps.getEpoch.outputs.epoch }}
      - name: Create Index File
        run: cd trivy-reports && tree -H . -o index.html
      - name: Publish Report
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Publishing trivy-report ${{ steps.getEpoch.outputs.epoch }}"
          git push


